import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import FAQ from "@/container/FAQ";
import Form from "@/container/Form";
import Company from "@/container/Company";

const inter = Roboto({
   subsets: ["latin"],
   weight: "400"
});

export const metadata: Metadata = {
   title: "Wepro | Home",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <Header />
            {children}
            
            <Footer />
         </body>
      </html>
   );
}
